
name: Environments build and test 

on: 
  push:
    branches:
      - 'dev_fission'
  pull_request:
    branches:
      - 'dev_fission'

jobs:
  # Job to run change detection
  buildenv:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: .github/filters.yaml


    - name:  python
      if: steps.filter.outputs.python == 'true'
      uses: hiberbee/github-action-skaffold@1.4.0
      with:
        command: run
        profile: python

    

    - name: Build and Push Docker
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: msat1234/dibas
        tags: v1,latest
        registry: docker.io
        dockerfile: ./environments/python/Dockerfile
        username: "msat1234"
        password: "Msat1234#" 


