
name: Images build series for Environment  

on: 
  push:
    branches:
      - 'master'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: docker build binary 
      run: |
        docker build ./binary -t fission/binary:latest

    - name: docker build python
      run: |
        docker build ./python -t fission/python:latest

    - name: docker build golang
      run: |
        docker build ./go -t fission/golang:latest

    - name: docker build nodejs
      run: |
        docker build ./nodejs -t fission/nodejs:latest

    - name: docker build perl
      run: |
        docker build ./perl -t fission/perl:latest

    - name: docker build php7
      run: |
        docker build ./php7 -t fission/php7:latest

    - name: docker build ruby
      run: |
        docker build ./ruby -t fission/ruby:latest

    - name: docker push
      run: |
        docker push fission/binary:latest
        docker push fission/python:latest
        docker push fission/golang:latest
        docker push fission/nodejs:latest
        docker push fission/perl:latest
        docker push fission/php7:latest
        docker push fission/ruby:latest

        

