name: Images build series for Environment  

on: 
  push:
    branches:
      - 'dev_fission'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
        DOCKER_BUILDKIT: 1
        BUILDX_PLATFORMS: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6 
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: install buildx
      command: |
        BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64"
        BUILDX_PLATFORMS ="linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6"

        curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"

        mkdir -p ~/.docker/cli-plugins

        mv docker-buildx ~/.docker/cli-plugins/
        chmod a+x ~/.docker/cli-plugins/docker-buildx

        docker buildx install
        # Run binfmt
        docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"

    - name: docker build python
      run: |
        docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 -t msat1234/dibas:python_Arch ./python
        docker buildx build --push  msat1234/dibas:python_Arch


    
    

    

  