
name: Images build series for Environment  

on: 
  push:
    branches:
      - 'dev_fission'
  pull_request:
    branches:
      - 'dev_fission'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: "msat1234"   
        DOCKER_PASSWORD: "Msat1234#"  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: docker build binary 
      run: |
        docker build ./binary -t msat1234/dibas:binary_latest

    - name: docker build dotnet
      run: |
        docker build ./dotnet -t msat1234/dibas:dotnet_latest

    - name: docker build python
      run: |
        docker build ./python -t msat1234/dibas:python_latest

    - name: docker build golang
      run: |
        docker build ./go -t msat1234/dibas:golang_latest

    - name: docker build jvm
      run: |
        docker build ./jvm -t msat1234/dibas:jvm_latest

    - name: docker build jvm-jersey
      run: |
        docker build ./jvm-jersey -t msat1234/dibas:jvm-jersey_latest

    - name: docker build nodejs
      run: |
        docker build ./nodejs -t msat1234/dibas:nodejs_latest

    - name: docker build perl
      run: |
        docker build ./perl -t msat1234/dibas:perl_latest

    - name: docker build php7
      run: |
        docker build ./php7 -t msat1234/dibas:php7_latest

    - name: docker build ruby
      run: |
        docker build ./ruby -t msat1234/dibas:ruby_latest

    - name: docker build tensorflow-serving
      run: |
        docker build ./tensorflow-serving -t msat1234/dibas:tensorflow-serving_latest

    - name: docker build dotnet20
      run: |
        docker build ./dotnet20 -t msat1234/dibas:dotnet20_latest

    
    

    - name: docker push
      run: |
        docker push msat1234/dibas:binary_latest
        docker push msat1234/dibas:dotnet_latest
        docker push msat1234/dibas:python_latest
        docker push msat1234/dibas:golang_latest
        docker push msat1234/dibas:jvm_latest
        docker push msat1234/dibas:jvm-jersey_latest
        docker push msat1234/dibas:nodejs_latest
        docker push msat1234/dibas:perl_latest
        docker push msat1234/dibas:php7_latest
        docker push msat1234/dibas:ruby_latest
        docker push msat1234/dibas:tensorflow-serving_latest
        docker push msat1234/dibas:dotnet20
        

