
name: Images build series for Environment  

on: 
  push:
    branches:
      - 'master'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: docker build binary 
      run: |
        docker build ./binary -t fission/binary:binary_latest

    - name: docker build python
      run: |
        docker build ./python -t fission/python:python_latest

    - name: docker build golang
      run: |
        docker build ./go -t fission/golang:golang_latest

    - name: docker build nodejs
      run: |
        docker build ./nodejs -t fission/nodejs:nodejs_latest

    - name: docker build perl
      run: |
        docker build ./perl -t fission/perl:perl_latest

    - name: docker build php7
      run: |
        docker build ./php7 -t fission/php7:php7_latest

    - name: docker build ruby
      run: |
        docker build ./ruby -t fission/ruby:ruby_latest

    - name: docker push
      run: |
        docker push fission/binary:binary_latest
        docker push fission/python:python_latest
        docker push fission/golang:golang_latest
        docker push fission/nodejs:nodejs_latest
        docker push fission/perl:perl_latest
        docker push fission/php7:php7_latest
        docker push fission/ruby:ruby_latest

        

